### ISSUE TITLE
Mailchimp double Opt-In language

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-mailchimp#11]
It is possible to set the users language through the "mc_language" merge field. But Mailchimp seems to have a bug where you have to set the `Accept-Language` header to force the opt-in mails in the correct language.

See https://stackoverflow.com/questions/13178685/possible-to-provide-a-subscribers-language-through-mailchimp-api, even tho the answer is from 2014.

Would it be possible to add this to the module? For example if the `mc_language` field is given.

**Comment by nadar** [comment]
Huhh? The subscription is done by API which will lose any env informations like request headers. https://github.com/luyadev/luya-module-mailchimp/blob/master/src/helpers/MailchimpHelper.php 

Maybe there are some docs or issues in the library we use? mailchimp/mailchimp

**Comment by nadar** [comment]
I just checked the library we use, this https://packagist.org/packages/mailchimp/mailchimp - its even hosted on bitbucket, what was the reason to choose this library @martinpetrasch?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
